name: book
channels:
  - conda-forge
dependencies:
  - pip
  - python==3.11
  - pip:
    - repo2data>=2.6.0
    - jupyter-book==0.14.0
    - afqinsight>=0.7.1
    - pyAFQ @ git+https://github.com/36000/pyAFQ@c50c0c4d05dc4f70699754a5f73047a4b4ff37b3
    - dipy
    - ray
    - trx-python==0.3
    - jupyter-server<2.0.0
    - dash
    - cvxpy
    - fury==0.12
    - tqdm
  