name: deploy-book

# Run this when the master or main branch changes
on:
  push:
    branches:
    - main

permissions:
  pages: write
  id-token: write

# This job installs dependencies, builds the book, and pushes it to `gh-pages`
jobs:
  deploy-book:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -l {0}
    permissions:
      pages: write
      id-token: write
    steps:
    - uses: actions/checkout@v3
    - uses: conda-incubator/setup-miniconda@v3
      with:
        environment-file: binder/environment.yml
        miniforge-version: latest
    - name: Create env and build the book
      run:
        jupyter-book build content

    # Upload the book's HTML as an artifact
    - name: Upload artifact
      uses: actions/upload-pages-artifact@v3
      with:
        path: "content/_build/html"

    - name: Publish docs to Github Pages
      uses: JamesIves/github-pages-deploy-action@v4
      with:
        folder: content/_build/html